name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you're using for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Specify your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site with Jekyll
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Directory where Jekyll builds the site
